### ISSUE TITLE
Solve SLF4J warning

### ISSUE THREAD

**Issue by ilgrosso** [tmess567/SYNCOPE-809#16]
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://912.fwk1282473384:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://912.fwk1282473384:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

This is likely happening because both log4j 2.x (as from Syncope) and other SLF4J concrete loggers are injected; please remove the latter.

**Comment by tmess567** [comment]
These warnings are being generated due to multiple instances of slf4j jars being added as plugins in the default target platform used while running the plugin. These jars are:
ch.qos.logback.slf4j
org.slf4j.api

This doesn't conflict with log4j; this is caused because 

> SLF4J API is designed to bind with one and only one underlying logging framework at a time. If more than one binding is present on the class path, SLF4J will emit a warning, listing the location of those bindings.

See: http://www.slf4j.org/codes.html#multiple_bindings

**Although I believe this should not be a problem (log4j should work with this)**, this can be solved by the following methods:

**1. Edit Run Configurations**
![image](https://cloud.githubusercontent.com/assets/9494086/16407539/e4c26eca-3d31-11e6-9f6d-7977c025d2d9.png)
Before running the eclipse application, edit the packaged plugins and remove ch.qos.logback.slf4j

**2. Create new Target Platform**
![image](https://cloud.githubusercontent.com/assets/9494086/16407783/1b2bde32-3d33-11e6-9957-6577da548c6f.png)
Go to Windows > Preferences > Plug-In Development > Target Platform > Add
Select Default: Default target for the running platform
Click Next and go to Content tab and deselect ch.qos.logback.slf4j then click on finish and select this platform as the active one.

**It would be great if you could provide me a way to test if log4j is working with this.**

**Comment by ilgrosso** [comment]
Remove logback, add log4j2.xml in the classpath

**Comment by tmess567** [comment]
ch.qos.logback.slf4j is not available in the classpath nor in my entire project, but available in eclipse installation itself as a plugin in the default target platform (The eclipse instance on which the plugin runs).  
I could provide an importable target file with the project, but I don't think this is necessary.

log4j-api-2.6.1.jar is already available in the classpath. I tested it out and it works.
![image](https://cloud.githubusercontent.com/assets/9494086/16409096/7fb5d244-3d39-11e6-8227-9f646c29088a.png)
The error listed above has been generated using log4j itself. I will add all exceptions to be reported through log4j as well in the next commit

**Comment by ilgrosso** [comment]
> ch.qos.logback.slf4j is not available in the classpath nor in my entire project, but available in eclipse installation itself as a plugin in the default target platform

Understand, so don't bother for the moment.
