### ISSUE TITLE
Dynamically generate entries for MANIFEST.MF

### ISSUE THREAD

**Issue by ilgrosso** [tmess567/SYNCOPE-809#5]
The [MANIFEST.MF](https://github.com/tmess567/SYNCOPE-809/blob/master/bundles/org.apache.syncope.ide.eclipse.plugin/META-INF/MANIFEST.MF) contains dependency versions which could dynamically be derived from `pom.xml` via resouce filtering.

**Comment by alexander-perucci** [comment]
The `MANIFEST.MF` can be automatically generated using http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html but I'm not sure if it is the best way.

**Comment by ilgrosso** [comment]
There are more (simpler) ways to generated it, for example having some sort of skeleton on which you can empower Maven resource filtering.

**Comment by ilgrosso** [comment]
I have seen your changes to that [pom.xml](https://github.com/tmess567/SYNCOPE-809/blob/master/bundles/org.apache.syncope.ide.eclipse.plugin/pom.xml): it is an improvement anyway, but dependency versions are still static, while most of them could be derived from the parent Syncope POM: for example, you should use `${cxf.version}` rather than `3.1.6`.

**Comment by tmess567** [comment]
Will be working on making the build files dynamic today.

**Comment by tmess567** [comment]
Please verify if this is resolved with this commit: [a8da3ce07a0cf6313859708272ef8bd679e1adb1](https://github.com/tmess567/SYNCOPE-809/commit/a8da3ce07a0cf6313859708272ef8bd679e1adb1)

**Comment by ilgrosso** [comment]
Looks good: once this code will be eventually part of Syncope codebase, you will also be able to remove the various version properties, as they will be inherited from the root Syncope POM file.

**Comment by tmess567** [comment]
Hey, @ilgrosso I would like to direct your attention to #9 by @prednaxela which could be the right way of packaging an eclipse plugin as a maven project since it would allow tycho to handle the build process. However from the testing I've done (listed in #9), this technique might need a MANIFEST.MF file to be present (even if it is empty). I've tried placing the generator executions on various phases and also copying the file into the main project from another sample project added to the parent pom and set to execute before the main SYNCOPE-809 project.

I propose that I put an empty MANIFEST.MF file in the project and during the plugin execution, populate it with the latest versions of the libraries being used. This would solve the problem of providing updated version numbers of libraries in the manifest file while allowing tycho to handle the eclipse plugin build process.

**Comment by ilgrosso** [comment]
An empty manifest being populated with dynamic values from pom sounds acceptable.

I'll have some time for looking properly at this on Friday, thanks.
