### ISSUE TITLE
Packaging for Eclipse Plugins that are bundle or fragments

### ISSUE THREAD

**Issue by alexander-perucci** [tmess567/SYNCOPE-809#9]
Tycho knows how to build Eclipse plug-ins by setting the packaging type to eclipse-plugin and not pom as I have suggested for #4.
You can see also here: http://wiki.eclipse.org/Tycho/Reference_Card#Bundle.2C_Fragments

**Comment by tmess567** [comment]
I've made the changes and pushed them to the new branch name [eclipse-plugin](https://github.com/tmess567/SYNCOPE-809/tree/eclipse-plugin) .

However, I needed to put back the build.properties and the MANIFEST.MF files to manage to build it (See issue #6 and #5 ). I tried moving around the plugin for copying these files in different phases but MANIFEST.MF is apparantly required inherently to an eclipse-plugin packaged project. On the other hand, when I try to generate build.properties on the fly, it shows the following error:
`bin.includes value(s) must be specified.`
However, on manual checking, this is already specified in the build.properties file.

Do you have any solution for these?

**Comment by alexander-perucci** [comment]
You can try to generate `MANIFEST.MF` and `build.properties` files outside the project that has `eclipse-plugin` setted in the POM. Then you can tell Maven to compile this project before all other projects and copy the generated `MANIFEST.MF` and `build.properties` and, `libs` into the specific folders of the project that has `eclipse-plugin` setted in the POM.

**Comment by tmess567** [comment]
Problem is, this looks for MANIFEST.MF and throws the following error while "Scanning for projects...", even before any project plugins are executed.

`[INFO] Scanning for projects...
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/tmess/Documents/githubproj
ects/trialpredsolve/SYNCOPE-809/bundles/org.apache.syncope.ide.eclipse.plugin/META-INF/MANIFEST.MF: Manifest file not found -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST
 /home/tmess/Documents/githubprojects/trialpredsolve/SYNCOPE-809/bundles/org.apache.syncope.ide.eclipse.plugin/META-INF/MANIFEST.MF: Manifest file not
 found
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/tmess/Documents/githubprojects/trialpre
dsolve/SYNCOPE-809/bundles/org.apache.syncope.ide.eclipse.plugin/META-INF/MANIFEST.MF: Manifest file not found
        at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromDirectory(DefaultBundleReader.java:95)
        at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest(DefaultBundleReader.java:59)
        at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest(DefaultBundleReader.java:50)
        at org.eclipse.tycho.core.osgitools.OsgiBundleProject.readArtifactKey(OsgiBundleProject.java:147)
        at org.eclipse.tycho.core.osgitools.OsgiBundleProject.setupProject(OsgiBundleProject.java:142)
        at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject(DefaultTychoResolver.java:74)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:90)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        ... 11 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException`

**Comment by alexander-perucci** [comment]
If you assume to have the latest MANIFEST.MF generated into the META-INF folder, have you the same errors ?

**Comment by tmess567** [comment]
I've tried that too. That's when I get the 
`bin.includes value(s) must be specified.`
error as stated above. I've checked the build.properties file, the contents are as expected:

```
source.. = src/main/java/
output.. = bin/
bin.includes = plugin.xml,\
     META-INF/,\
     .,\
     src/main/resources/icons/,\
     contexts.xml,\
     target/lib/asm-5.0.4.jar,\
     target/lib/commons-codec-1.10.jar,\
     target/lib/commons-collections4-4.1.jar,\
     target/lib/commons-lang3-3.4.jar,\
     target/lib/cxf-core-3.1.6.jar,\
     target/lib/cxf-rt-databinding-jaxb-3.1.6.jar,\
     target/lib/cxf-rt-frontend-jaxrs-3.1.6.jar,\
     target/lib/cxf-rt-rs-client-3.1.6.jar,\
     target/lib/cxf-rt-rs-extension-search-3.1.6.jar,\
     target/lib/cxf-rt-transports-http-3.1.6.jar,\
     target/lib/cxf-rt-wsdl-3.1.6.jar,\
     target/lib/jackson-annotations-2.7.0.jar.jar,\
     target/lib/jackson-core-2.7.5.jar.jar,\
     target/lib/jackson-databind-2.7.5.jar.jar,\
     target/lib/jackson-datatype-joda-2.7.5.jar.jar,\
     target/lib/jackson-jaxrs-base-2.7.5.jar.jar,\
     target/lib/jackson-jaxrs-json-provider-2.7.5.jar.jar,\
     target/lib/jackson-module-jaxb-annotations-2.7.5.jar.jar,\
     target/lib/javax.annotation-api-1.2.jar,\
     target/lib/javax.ws.rs-api-2.0.1.jar,\
     target/lib/jaxb-core-2.2.11.jar,\
     target/lib/jaxb-impl-2.2.11.jar,\
     target/lib/joda-time-2.4.jar,\
     target/lib/log4j-api-2.6.1.jar,\
     target/lib/slf4j-api-1.7.21.jar,\
     target/lib/stax2-api-3.1.4.jar,\
     target/lib/syncope-client-lib-2.0.0-SNAPSHOT.jar,\
     target/lib/syncope-common-lib-2.0.0-SNAPSHOT.jar,\
     target/lib/syncope-common-rest-api-2.0.0-SNAPSHOT.jar,\
     target/lib/validation-api-1.1.0.Final.jar,\
     target/lib/woodstox-core-asl-4.4.1.jar,\
     target/lib/wsdl4j-1.6.3.jar.jar,\
     target/lib/xmlschema-core-2.2.1.jar,\
     target/lib/commons-io-1.3.2.jar

```

I moved the following plugin from the org.apache.syncope.ide.eclipse.plugin (named SYNCOPE-809) project to the bundles project

```
<plugin>
  <artifactId>maven-resources-plugin</artifactId>
  <version>3.0.1</version>
  <executions>
    <execution>
      <phase>validate</phase>
      <id>copy-build.properties</id>
      <goals>
        <goal>copy-resources</goal>
      </goals>
      <configuration>
        <outputDirectory>org.apache.syncope.ide.eclipse.plugin</outputDirectory>
        <resources>          
          <resource>
            <filtering>true</filtering>
            <directory>org.apache.syncope.ide.eclipse.plugin/src/main/resources</directory>
            <includes>
              <include>build.properties</include>
            </includes>

          </resource>
        </resources>              
      </configuration>            
    </execution>
    <execution>
      <phase>validate</phase>
      <id>copy-manifest.mf</id>
      <goals>
        <goal>copy-resources</goal>
      </goals>
      <configuration>
        <outputDirectory>org.apache.syncope.ide.eclipse.plugin/META-INF</outputDirectory>
        <resources>          
          <resource>
            <filtering>true</filtering>
            <directory>org.apache.syncope.ide.eclipse.plugin/src/main/resources</directory>
            <includes>
              <include>MANIFEST.MF</include>
            </includes>

          </resource>
        </resources>              
      </configuration>            
    </execution>
  </executions>
</plugin>
```

and pre placed the MANIFEST.MF file manually. I've tried this with and without the `copy-manifest.mf` execution.

**Comment by alexander-perucci** [comment]
Have you tried to execute `copy-build.properties` and `copy-manifest.mf` before maven validate phase ? You can see the Maven Lifecycle Reference section https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

**Comment by tmess567** [comment]
The build.properties file was accepted this time, by placing it's execution in the pre-clean phase. However, without the MANIFEST.MF file, maven throws an error even before the pre-clean phase. I believe that is the earliest phase possible to put a plugin into. I even tried executing the resources:copy-resources goal directly, but faced the same error. Is there some workaround to this?

**Comment by alexander-perucci** [comment]
Have you an error about the MANIFEST.MF file even if you put the latest generated Manifest file in the META-INF folder ?

If yes, you can try (just to test and get some suggestions about a possible solution) to create a folder named `extra` in the root folder (same level of `bundles`folder) and put into this folder a POM that contains rules to copy dependencies, create build.properties and MANIFEST.MF. Set <phase>package</phase> instead of pre-clean phase. Then in the POM that contains <module>bundles</module> add  <module>extra</module> before bundles module.

**Comment by tmess567** [comment]
If I manually place the MANIFEST.MF file in the META-INF folder and run `mvn clean verify`, the project builds successfully (using pre-clean phase). The problem is with generating the MANIFEST.MF file. 
Anyways, I tried the above solution but got the same error.

**Comment by tmess567** [comment]
It works if I first run `mvn clean verify` inside the extra folder and then run it on the entire package. This however would create problems when this project is added to the apache syncope source.

I believe this works because upon scanning the project named extra, it does not have to scan through the eclipse-plugin packaged part, so it generates the META-INF and MANIFEST.MF and then the entire project can be built.

**Comment by tmess567** [comment]
This comment is also in reference to #5 and #20 
The first build of the project still fails as stated in #20 . This is caused because on running `mvn clean verify`, the tycho plugin apparently picks up the MANIFEST and builds the entire project with it, **without picking up any changes made to the MANIFEST.MF file**

I tried various other possibilities but eventually failed.

> Limitations
> It is not possible to mix pom-first and manifest-first projects in the same reactor build.
> Dependency resolution happens very early during maven build, before execution of build lifecycle of any project and well before bundle manifests can be generated for pom-first projects. To resolve dependencies of manifest-first projects, however, Tycho needs to to read bundle manifests of all pom-first artifacts.
> This limitation cannot be relaxed without fundamental changes to Maven build lifecycle. Currently, the only solution is to build pom-first projects separately, before building manifest-first projects.

You can view the above text at the **Wiki for Tycho** [here](https://wiki.eclipse.org/Tycho/How_Tos/Dependency_on_pom-first_artifacts).

I realize that this might not be compatible with the syncope project but, would it be possible to run the following commands while building

```
mvn initialize
mvn clean verify
```

This would allow the MANIFEST to be generated and then picked up in the second run for compiling this.

If this is not acceptable, I believe we should stick to the pom packaging and continue with the project.

**Comment by ilgrosso** [comment]
The issue above looks very similar to what I had the chance to discuss with @prednaxela.

I see as higher priority the possibility to incorporate the outcome of this project as Apache Syncope Maven submodule so that the whole build is working via standard

```
mvn clean install
```

e.g. the sequence of two separated Maven invocations reported above is not acceptable.

Moreover, I'd say that this

> It is not possible to mix pom-first and manifest-first projects in the same reactor build.

says enough.

I think you need now to focus on refactoring the code for inclusion in the Syncope codebase as stated above, and set expectations accordingly.
If this implies not being able to dynamically generated the MANIFEST, then we'll have to deal with this.

This also means that you need to provide a way for generating a p2 site that can be published somewhere (ideally under [this path](https://www.apache.org/dist/syncope/2.0.0-M4/) for 2.0.0-M4, for example) for remotely installing your plug-in into an existing Eclipse instance.

**Comment by tmess567** [comment]
OK, I will rollback my last commit and package this as a pom-first project. This would mean that to generate an installable jar of the plugin, the project will need to be built on an eclipse installation.
I will start working on the p2 site right away.

**Comment by ilgrosso** [comment]
Sorry, this won't work either: the only requirement for building Apache Syncope **must** remain Maven.

Maybe I am a bit lost here: could you please summarize the options attempted so far with their compliance with what expressed above and problems encountered? Thanks!

**Comment by tmess567** [comment]
AFAIK the pom-first project should be compatible with syncope (I will be testing this asap) since it only requires the `mvn clean install` command to build. My only concern is that the jar generation is not a part of the build process.

There are 2 ways of creating a tycho project,
- **Pom-first** -> Maven compilation, the class files are generated but this would not generate a jar for the eclipse installation
- **Manifest-first** -> Tycho specific compilation, the dependencies are handled by the MANIFEST.MF file and an installable jar is generated

Comparisons between the 2 can be found in the [tycho wiki](https://wiki.eclipse.org/Tycho/How_Tos/Dependency_on_pom-first_artifacts) and also in this [stackoverflow answer](http://stackoverflow.com/a/11373010).

The current issue relates to the second method and the problems faced during the same. Listed below, are the attempts made in configuring the project as a Manifest-first project while dynamically fetching dependency versions from the properties listed in pom to allow version changes to be done from a single location.
1. Generating the Manifest file (and the build.properties file) **from a skeleton** by populating it with the required values. This failed since the existence of the manifest file is checked before any configurable phase of maven is run.
2. Generating the Manifest file **from the parent pom** assuming the some phase of the parent module is executed before the manifest check. This failed for the same reason as above.
3. Generating the Manifest file **from a separate module** on the same level as the main project assuming the some phase of this module is executed before the manifest check. This failed for the same reason as above.
4. Generating the Manifest file while **placing a dummy manifest file** in the project which is changed upon phase execution of the module or it's parent module. This failed since the dummy manifest is cached upon the start of the build and maintained throughout.

**Comment by alexander-perucci** [comment]
@ilgrosso yes this is the problem that I have discussed with you. @tmess567 the use of pom-first or manifest-first depends of your project structure. There are some pros and cons using the first one or second one but in my opinion this is no the case. As you said, the real problem is that if you auto-generate the MANIFEST.MF file maven cached it and you have an error if you run `mvn clean verify` at the first time. If you run the same command at the second time you should not have an error. 

If you run `mvn clean` and then `mvn verify` you don't have any errors because the `clean` phase is executed in all modules and the MANIFEST.MF is generated then the `verify` pahse is executed in all modules (without re-generate the MANIFEST file) and the MANIFEST.MF file (generated during the `clean` phase) will be cached.

I don't have the solution for now :(, I'm investigating to use Apache Maven AntRun Plugin to solve the issue. When I solve the issue I'll let you know :)

**Comment by tmess567** [comment]
Thanks for the input and help. :smiley: I couldn't have explained it any better.

**Comment by ilgrosso** [comment]
Ok, it's little clearer now (but how complex is Eclipse's relationship with Maven? it must be really unnatural...).

What are the consequences of choosing the pom-first approach? What does "not generate a jar for the eclipse installation" exactly mean?
Can we "compensate" with another submodule for the p2 site?

**Comment by tmess567** [comment]
I am still reading about p2 repositories, but here's what I know.
By changing the directory structure a bit, I can allow generation of a p2 repo by issuing the following command

```
$ECLIPSE -debug -consolelog -nosplash -verbose -application org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher -metadataRepository file:$DEST -artifactRepository file:$DEST -source %SRC% -compress -append -publishArtifacts
```

This [blog post](http://maksim.sorokin.dk/it/2010/11/26/creating-a-p2-repository-from-features-and-plugins/) illustrates what is required.

This would mean that given the source code of my project, a person **could** issue the above command and generate a p2 repository which should be installable in eclipse. This should work with the pom-first method, but I am still testing it.

**Comment by ilgrosso** [comment]
@tmess567 there should be some Maven magic for generating p2 sites as well, @prednaxela should be aware of this

If this is correct, I don't see valid reasons for not embracing the pom-first approach; am I wrong?

**Comment by ilgrosso** [comment]
What about https://wiki.eclipse.org/Tycho/eclipse-repository ?

**Comment by tmess567** [comment]
The above link does not accept a path to the plugin. This indicates that the plugin's pom should have an **eclipse-plugin** packaging to ensure that it is recognized by the build process of tycho.

An eclipse-plugin packaging requires a manifest-first approach, but I will try this out nonetheless.

**Comment by alexander-perucci** [comment]
@ilgrosso yes, as i suggested the project structure in #4 . This structure uses a simple parent pom with <packaging>pom</packaging>,  and you can see that in the releng folder there is a project with pom packaged with eclipse-repository (<packaging>eclipse-repository</packaging>). I strongly suggest to use tycho and related packaging type <packaging>...</packaging> for each plugins, feature, and update-site projects.

**Comment by ilgrosso** [comment]
@prednaxela I understand, but isn't such approach not completely in-line with Maven build? Aren't you still finding a way to make it successful via the antrun plugin (as said above)?

**Comment by ilgrosso** [comment]
ok @tmess567 let's proceed as @prednaxela suggests, **without** generating the `MANIFEST.MF`: we'll open a separate improvement for this.

WDYT?

**Comment by tmess567** [comment]
OK, I will start with the restructuring.

**Comment by ilgrosso** [comment]
Thanks @tmess567 : once done please migrate everything in your own Syncope fork

**Comment by tmess567** [comment]
I had a run in again without alternate builds working due to incompatibility between tycho and the copy-dependencies of maven. This bug in tycho is described [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=393978).

So I used the workarounds and also came across the option
`<stripVersion>true</stripVersion>`
 for copy-dependencies which essentially generates asm.jar instead of asm-<version number>.jar I believe this solves the problem of dynamic generation of manifest and build properties files which should no longer be needed.

But to address the above issue caused by the bug, I had to move all the dependencies from target/lib to lib/ which is a workaround for the bug listed above. Please have a look at the latest commit, so I can merge this with master. I am currently running tests on my syncope fork to ensure that this works with that as well, which it should.

**Comment by ilgrosso** [comment]
> But to address the above issue caused by the bug, I had to move all the dependencies from target/lib to lib/ which is a workaround for the bug listed above.

Understood; ok, there are worse things in this world...

> Please have a look at the latest commit, so I can merge this with master.

After pulling and moving to the `eclipse-repo-packaging` branch, I've built via `mvn clean verify` then opened Eclipse, selected "Install new software" and provided `/home/ilgrosso/work/syncope/SYNCOPE-809/releng/org.apache.syncope.ide.eclipse.site/target/repository` as location.

Everything worked as expected then: after finishing installation Eclipse restarted and I was able to open the Syncope view, where I have also appreciated the new HTML and XSLT editors.

Nice job!
